name: eden_demo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  ably_flutter: ^1.2.23
  cached_network_image: ^3.3.0
  faker: ^2.1.0
  firebase_auth: ^4.13.0
  firebase_core: ^2.22.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.6
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.6
  rxdart: ^0.27.7
  shimmer: ^3.0.0
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.4.5
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
